### PR TITLE
Backport crash fix

### PR DESCRIPTION
**Pull request by jreidinger**

### CODE REVIEW

**Comment by teclator** [comment]
It basically backports  #93

**Comment by lslezak** [comment]
BTW yet another example which could have been caught by https://github.com/yast/yast-rear/pull/8...

**Comment by jreidinger** [comment]
@lslezak well, it expect some clicking to advanced settings, so I still worry we are getting into area of openQA

**Comment by lslezak** [comment]
But as you can see it is not handled in openQA at all...

**Comment by jreidinger** [comment]
@lslezak yes, as test missing in openQA. So we have option to write it in openQA or create new framework and write it there. To be honest I am not sure if own framework is better option.

**Pull request merged**
